version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - mercurial
    - graphviz
    - python3-pip
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - /usr/bin/python3 -m pip install hg-git
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --no-root
      - python -m bash_kernel.install
    pre_build:
      - jupyter-book config sphinx book/

sphinx:
  configuration: book/conf.py
  builder: html
  fail_on_warning: true
